#!/bin/bash

# directory tree - http://www.shell-fu.org/lister.php?id=209  
alias dirf='find . -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"'    
  
#compare files using comm (requires perl) - http://www.shell-fu.org/lister.php?id=186  
compare(){  
  comm $1 $2 | perl -pe 's/^/1: /g;s/1: \t/2: /g;s/2: \t/A: /g;' | sort  
}  
    
#calendar with today highlighted - http://www.shell-fu.org/lister.php?id=210  
alias tcal='cal | sed "s/^/ /;s/$/ /;s/ $(date +%e) / $(date +%e | sed '\''s/./#/g'\'') /"'  
  
# count files by type - http://www.shell-fu.org/lister.php?id=173  
alias ftype='find ${*-.} -type f | xargs file | awk -F, '\''{print $1}'\'' | awk '\''{$1=NULL;print $0}'\'' | sort | uniq -c | sort -nr'  
  
# convert permissions to octal - http://www.shell-fu.org/lister.php?id=205  
alias lo='ls -l | sed -e 's/--x/1/g' -e 's/-w-/2/g' -e 's/-wx/3/g' -e 's/r--/4/g' -e 's/r-x/5/g' -e 's/rw-/6/g' -e 's/rwx/7/g' -e 's/---/0/g''  
  
# portscan in one line - http://www.shell-fu.org/lister.php?id=295  
# portscan(){  
#   HOST="$1";for((port=1;port<=65535;++port));do echo -en "$port ";if echo -en "open $HOST $port\nlogout\quit" | telnet 2>/dev/null | grep 'Connected to' > /dev/null;then echo -en "\n\nport $port/tcp is open\n\n";fi;done  
# }  
  
  
# get an ordered list of subdirectory sizes - http://www.shell-fu.org/lister.php?id=275  
alias dux='du -sk ./* | sort -n | awk '\''BEGIN{ pref[1]="K"; pref[2]="M"; pref[3]="G";} { total = total + $1; x = $1; y = 1; while( x > 1024 ) { x = (x + 1023)/1024; y++; } printf("%g%s\t%s\n",int(x*10)/10,pref[y],$2); } END { y = 1; while( total > 1024 ) { total = (total + 1023)/1024; y++; } printf("Total: %g%s\n",int(total*10)/10,pref[y]); }'\'''  
  
# share current tree over the web - http://www.shell-fu.org/lister.php?id=54  
alias webshare='python -c "import SimpleHTTPServer;SimpleHTTPServer.test()"'  
    
# keep your home directory organised - http://www.shell-fu.org/lister.php?id=310  
export TD="$HOME/temp/`date +'%Y-%m-%d'`"  
td(){  
    td=$TD  
    if [ ! -z "$1" ]; then  
        td="$HOME/temp/`date -d "$1 days" +'%Y-%m-%d'`";  
    fi  
    mkdir -p $td; cd $td  
    unset td  
}  
  
calc(){ echo "${1}"|bc -l; }  

wm-info() { while ( true ); do xprop | egrep "(^WM_(CLASS|NAME))|WM_PID"; echo; done; }
  
ccopy(){ cp $1 /tmp/ccopy.$1; }  
alias cpaste="ls /tmp/ccopy* | sed 's|[^\.]*.\.||' | xargs -I % mv /tmp/ccopy.% ./%"  

extract () { 
    mkdir "$1.d"
    cd "$1.d"
    fn="../$1"
    if [ -f $fn ] ; then  
        case $1 in  
            *.tar.bz2)   tar xvjf $fn   ;;  
            *.tar.gz)    tar xvzf $fn   ;;  
            *.bz2)       bunzip2 $fn    ;;  
            *.rar)       unrar x $fn    ;;  
            *.gz)        gunzip $fn     ;;  
            *.tar)       tar xvf $fn    ;;  
            *.jar)       jar xvf $fn    ;;  
            *.war)       jar xvf $fn    ;;  
            *.tbz2)      tar xvjf $fn   ;;  
            *.tgz)       tar xvzf $fn   ;;  
            *.zip)       unzip $fn      ;;  
            *.Z)         uncompress $fn ;;  
            *.7z)        7z x $fn       ;;  
            *)           echo "'$!' cannot be extracted via >extract<" ;;  
        esac  
    else  
        echo "'$1' is not a valid file"  
    fi  
    cd ..
}  

#  alias connectioncount=netstat -an | grep ESTABLISHED | awk '{print $5}' | awk -F: '{print $1}' | sort | uniq -c | awk '{ printf("%s\t%s\t",$2,$1) ; for (i = 0; i < $1; i++) {printf("*")}; print ""}'
connections() {
    netstat -an | grep ESTABLISHED | awk '{print $5}' | awk -F: '{print $1}' | sort | uniq | xargs -i host {} | awk '{print $5}'
}

NOTESDIR=~/projects/the-library/project-planning/shell-notes

note() {
    declare notefile="$NOTESDIR/notes_$1.txt"
    echo "$notefile"
    touch "$notefile"
    cat <<EOF >> "$notefile"

[note ^^^^^^^^^^^^^^^^^^^^]
tags=$*
[history]
EOF

    history | tail -n 15 >> "$notefile"

    cat <<EOF >> "$notefile"
[/history]
[/note ____________________]


EOF

    emacsclient -n -nw "$notefile"
}  

nls() { 	
    ls -c "$NOTESDIR" | grep "$*" 
}


alias emacs='emacsclient-24.2 -n --alternate-editor=""'
alias visit='emacsclient-24.2 -n --alternate-editor=""'

killsbt() {
    PROCESS=`ps fUsaunders | grep java | grep sbt-launch`
    echo "killing process $PROCESS"
    echo $PROCESS | cut -b 1-8 | perl -pne 's/[^0123456789]//g' | xargs -i kill {}
}


# emacsd() {
#     ps -C "emacs-24.2" >/dev/null && echo "emacs running..." && return 1
#     echo 'please start emacs --daemon'
# }
# 
# ewin() {
#     ( emacsd $1 2>&1 >/dev/null ) || ( emacsclient -c -n )
# }
# visit() {
#     ( emacsd $1 2>&1 >/dev/null ) || ( emacsclient -n $1 )
# }


